### ISSUE TITLE
Базовая реализация интерфейса.

### ISSUE THREAD

**Issue by Kuprich** [andreisfedotov/Notes#1]
Здравствуйте, Спасибо большое за представленный проект, 

в процессе изучения возник вопрос:
имеется базовая реализация интерфейса IMapWith<T>

https://github.com/andreisfedotov/Notes/blob/34be5755a6c95fdbb808b82d93052c7a5e80bb7f/Notes.Backend/Notes.Application/Common/Mappings/IMapWith.cs#L5-L9

т.е. по умолчанию должен использоваться метод Mapping интерфейса, если он не описан в классе, который его раелизует.

в классе AssemblyMappingProfile вызываются как раз те самые методы Mapping у классов, реализующих интерфейс IMapWith<T>

Но, если в классе, (например CreateNoteDto) явно не реализовать метод Mapping, то в AssemblyMappingProfile когда будет создаваться экземпляр этого объекта, то метод Mapping из интерфейса не будет найден, и в MethodInfo возвратится null 

https://github.com/andreisfedotov/Notes/blob/34be5755a6c95fdbb808b82d93052c7a5e80bb7f/Notes.Backend/Notes.Application/Common/Mappings/AssemblyMappingProfile.cs#L21-L26

**Comment by vsnedro** [comment]
@ilyaik 
> Но, если в классе, (например CreateNoteDto) явно не реализовать метод Mapping, то в AssemblyMappingProfile когда будет создаваться экземпляр этого объекта, то метод Mapping из интерфейса не будет найден, и в MethodInfo возвратится null

Если в классе нет явной реализации метода, то найти его через рефлексию не получится, ведь этот метод не является членом класса. Тогда надо искать этот метод в интерфейсе с явной реализацией.

```
var methodInfo = type.GetMethod("Mapping")
    ?? type.GetInterface(typeof(IMapWith<>).Name)?.GetMethod("Mapping");
```

**Comment by andreisfedotov** [comment]
офигеть, почему я только сейчас увидел, что тут есть открытые обсуждения ._.

**Comment by Kuprich** [comment]
Спасибо))
