### ISSUE TITLE
Не понимаю, мне для каждой таблицы создавать по 14 классов?

### ISSUE THREAD

**Issue by AndreyAs44** [andreisfedotov/Notes#4]
Сижу и пытаюсь сделать по курсу свой проект. В нем 7 таблиц.  Почти для каждой таблицы необходимо сделать большую часть операций (таких как получение по id, получить все, добавить удалить обновить). Эти операции довольно однотипны. В примере 14 классов. Соответственно, 14*7=98, зачем мне создавать 98 классов с однотипным кодом? Правильно ли я всё понимаю по архитектуре в видео, как решить эту проблему? (Скорее всего ведь не надо создавать такое огромное кол-во классов, я что-то не понимаю, да и все делают абсолютно по разному, как и любую архитектуру, просто этот курс довольно понятный и простой)
![image](https://github.com/andreisfedotov/Notes/assets/74313991/eda24cc8-3dab-48e6-b525-230e06be0ebc)

**Comment by demndevel** [comment]
Как говорил один довольно мудрый человек, **_it depends_**. То есть, вы должны исходить из ваших нужд. Если у вас огромный проект со сложнейшей бизнес-логикой, то вам стоило бы пойти дальше этого видео и использовать [DDD](https://en.wikipedia.org/wiki/Domain-driven_design). Если вам надо как можно быстро сделать CRUD операции без дальнейших усложнений, то можно просто всё делать в MVC контроллерах.

В общем, не надо делать слои ради слоёв. Паттерны ради паттернов. И архитектуру ради архитектуры. Надо смотреть, приведёт ли тот или иной подход к дальнейшим проблемам.

**Comment by AndreyAs44** [comment]
Спасибо! Вы помогли немного по-другому взглянуть на все эти моменты и определиться что делать дальше)
